baseURL = 'https://yenn.love/'
languageCode = 'en-us'
title = '世界上最可爱的Yenn！'
theme = "timeline"
defaultTheme = "light" 
copyright = "Copyright by yenn & 咕噜冻"
[author]
  name = "制作by 传说中的洞洞"
  github = "https://github.com/lisirrx"


[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Content-Security-Policy = 'script-src localhost:1313'
    Referrer-Policy = 'no-referrer'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'