baseURL = 'https://yenn.love/'
languageCode = 'en-us'
title = '世界上最可爱的Yenn！'
theme = "timeline"
defaultTheme = "light" 
copyright = "Copyright by yenn & 咕噜冻"
[author]
  name = "制作by 传说中的洞洞"
  github = "https://github.com/lisirrx"
