baseURL = 'https://yenn.love/'
languageCode = 'en-us'
title = '世界上最可爱的Yenn！'
theme = "timeline"
defaultTheme = "light" 
copyright = "Copyright by yenn & 咕噜冻"
[author]
  name = "制作by 传说中的洞洞"
  github = "https://space.bilibili.com/15596485"

[params]
  upname = "yenn"
  daytotoday = "一百天"
  uplink = "https://space.bilibili.com/1192693417/"
